[package]
name = "lakesoul-io-c"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
lakesoul-io = { path = "../lakesoul-io" }
arrow = { version = "24.0.0", features = ["ffi"] }
tokio = { version = "1", features = ["full"] }
